In [36]:
print('Hello world')

Hello world

In [37]:
! pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opencv-python in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (4.13.0.92)
Requirement already satisfied: numpy>=2 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from opencv-python) (2.4.4)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import cv2
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    if not ret:
        break 
    cv2.flip(frame,1)
    cv2.imshow("Mirror Face Detection",frame)


    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [39]:
import cv2
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_defauly.xml'
)

cap = cv2.VideaCapture(0)
while True:
    ret, frame = cap.read()

    if not ret:
        break 

    frame = cv2.flip(frame, 1)

AttributeError: module 'cv2' has no attribute 'VideaCapture'

In [ ]:
def factorial(n):
    if n==1:
        return 1
    else:
        return n*factorial(n-1)

In [ ]:
print(factorial(5))

120

In [ ]:
import pandas as pd

In [ ]:
l1 = [1,2,3,4]

In [ ]:
l1.pop(3)

4

In [ ]:
print(l1)

[1, 2, 3]

In [ ]:
import pandas as pd

In [ ]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import numpy as np

In [ ]:
series1 = pd.Series(
    [10,20,30,40,50],
    index=['a','b','c','d','e']
)

In [ ]:
series1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
data = pd.DataFrame(series1)

In [ ]:
data

    0
a  10
b  20
c  30
d  40
e  50

In [ ]:
series2 = pd.Series({
    'Name':['Ram','Shyam','Mohan'],
    'Age':[50,40,30]
})

In [ ]:
series2

Name    [Ram, Shyam, Mohan]
Age            [50, 40, 30]
dtype: object

In [ ]:
df = pd.read_csv('student.csv')
print(df.head(2))
print(df.tail(2))

     name  age       city  score
0  Roshan   22  Atrauliya     34
1  Vikash   23     Deoria     43
       name  age       city  score
2  Prashant   19   Azamgarh     56
3     Vijay   20  Madiyapar     43

In [ ]:
df

       name  age       city  score
0    Roshan   22  Atrauliya     34
1    Vikash   23     Deoria     43
2  Prashant   19   Azamgarh     56
3     Vijay   20  Madiyapar     43

In [ ]:
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
 3   score   4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes
None
             age      score
count   4.000000   4.000000
mean   21.000000  44.000000
std     1.825742   9.055385
min    19.000000  34.000000
25%    19.750000  40.750000
50%    21.000000  43.000000
75%    22.250000  46.250000
max    23.000000  56.000000

In [ ]:
print(df.shape)
print(df.columns)
print(df.index)

(4, 4)
Index(['name', 'age', 'city', 'score'], dtype='str')
RangeIndex(start=0, stop=4, step=1)

In [62]:
import pandas as pd

In [ ]:
data1 = {
    'Name':['Roshan','Vikash','Akash','Rahul'],
    'Age':[20,25,30,22],
    'Classes':[10,12,9,10],
    'Marks':[25,65,45,36]
}

In [ ]:
df1 =pd.DataFrame(data1)

In [46]:
df1.loc[1,"Name"]

'Vikash'

In [55]:
import numpy as np
df1

     Name  Age  Classes  Marks
0  Roshan   20       10     25
1  Vikash   25       12     65
2   Akash   30        9     45
3   Rahul   22       10     36

In [69]:

df1.iloc[1,0]

'Vikash'

In [80]:
df1.loc[0,'Age']

np.int64(20)

In [70]:
import pandas as pd

In [67]:
data2 = {
    'Name':['Roshan','Vikash','Akash','Rahul'],
    'Age':[np.nan,25,30,22],
    'Classes':[10,np.nan,9,10],
    'Marks':[25,65,np.nan,36]
}

In [72]:
df2 = pd.DataFrame(data2)

In [73]:
df2

     Name   Age  Classes  Marks
0  Roshan   NaN     10.0   25.0
1  Vikash  25.0      NaN   65.0
2   Akash  30.0      9.0    NaN
3   Rahul  22.0     10.0   36.0

In [75]:
filling = df2.fillna(0)

In [76]:
filling

     Name   Age  Classes  Marks
0  Roshan   0.0     10.0   25.0
1  Vikash  25.0      0.0   65.0
2   Akash  30.0      9.0    0.0
3   Rahul  22.0     10.0   36.0

In [82]:
null = df2.isnull()

In [83]:
null

    Name    Age  Classes  Marks
0  False   True    False  False
1  False  False     True  False
2  False  False    False   True
3  False  False    False  False

In [86]:
df2.isnull().any()

Name       False
Age         True
Classes     True
Marks       True
dtype: bool

In [87]:
filling

     Name   Age  Classes  Marks
0  Roshan   0.0     10.0   25.0
1  Vikash  25.0      0.0   65.0
2   Akash  30.0      9.0    0.0
3   Rahul  22.0     10.0   36.0

In [88]:
df2['Age']=df2['Age'].fillna(df2['Age'].mean())

In [89]:
df2

     Name        Age  Classes  Marks
0  Roshan  25.666667     10.0   25.0
1  Vikash  25.000000      NaN   65.0
2   Akash  30.000000      9.0    NaN
3   Rahul  22.000000     10.0   36.0

In [90]:
op = {
    'Name':['Roshan','Vikash','Akash','Rahul'],
    'Age':[20,25,30,22],
    'Classes':[10,12,9,10],
    'Marks':[25,65,45,36]
}

In [93]:
emp = pd.DataFrame(op)

In [94]:
emp

     Name  Age  Classes  Marks
0  Roshan   20       10     25
1  Vikash   25       12     65
2   Akash   30        9     45
3   Rahul   22       10     36

In [102]:
emp['Bonus']=emp['Marks']*2
print(emp)

     Name  Age  Classes  Marks  Bonus
0  Roshan   20       10     25     50
1  Vikash   25       12     65    130
2   Akash   30        9     45     90
3   Rahul   22       10     36     72

In [107]:
emp['Age_Next_year']=emp['Age']+1

In [108]:
emp

     Name  Age  Classes  Marks  Bonus  Age_Next_year
0  Roshan   20       10     25     50             21
1  Vikash   25       12     65    130             26
2   Akash   30        9     45     90             31
3   Rahul   22       10     36     72             23

In [115]:
emp['Age'],emp['Age_Next_year']

(0    20
 1    25
 2    30
 3    22
 Name: Age, dtype: int64,
 0    21
 1    26
 2    31
 3    23
 Name: Age_Next_year, dtype: int64)

In [121]:
emp[['Age', 'Age_Next_year']]

   Age  Age_Next_year
0   20             21
1   25             26
2   30             31
3   22             23