In [ ]:
print('Hello world')

Hello world

In [ ]:
! pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opencv-python in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (4.13.0.92)
Requirement already satisfied: numpy>=2 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from opencv-python) (2.4.4)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import cv2
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    if not ret:
        break 
    cv2.flip(frame,1)
    cv2.imshow("Mirror Face Detection",frame)


    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_defauly.xml'
)

cap = cv2.VideaCapture(0)
while True:
    ret, frame = cap.read()

    if not ret:
        break 

    frame = cv2.flip(frame, 1)

AttributeError: module 'cv2' has no attribute 'VideaCapture'

In [ ]:
def factorial(n):
    if n==1:
        return 1
    else:
        return n*factorial(n-1)

In [ ]:
print(factorial(5))

120

In [ ]:
import pandas as pd

In [ ]:
l1 = [1,2,3,4]

In [ ]:
l1.pop(3)

4

In [ ]:
print(l1)

[1, 2, 3]

In [ ]:
import pandas as pd

In [ ]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\NAYA PRAYOG\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import numpy as np

In [ ]:
series1 = pd.Series(
    [10,20,30,40,50],
    index=['a','b','c','d','e']
)

In [ ]:
series1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
data = pd.DataFrame(series1)

In [ ]:
data

    0
a  10
b  20
c  30
d  40
e  50

In [ ]:
series2 = pd.Series({
    'Name':['Ram','Shyam','Mohan'],
    'Age':[50,40,30]
})

In [ ]:
series2

Name    [Ram, Shyam, Mohan]
Age            [50, 40, 30]
dtype: object

In [ ]:
df = pd.read_csv('student.csv')
print(df.head(2))
print(df.tail(2))

     name  age       city  score
0  Roshan   22  Atrauliya     34
1  Vikash   23     Deoria     43
       name  age       city  score
2  Prashant   19   Azamgarh     56
3     Vijay   20  Madiyapar     43

In [ ]:
df

       name  age       city  score
0    Roshan   22  Atrauliya     34
1    Vikash   23     Deoria     43
2  Prashant   19   Azamgarh     56
3     Vijay   20  Madiyapar     43

In [ ]:
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
 3   score   4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes
None
             age      score
count   4.000000   4.000000
mean   21.000000  44.000000
std     1.825742   9.055385
min    19.000000  34.000000
25%    19.750000  40.750000
50%    21.000000  43.000000
75%    22.250000  46.250000
max    23.000000  56.000000

In [ ]:
print(df.shape)
print(df.columns)
print(df.index)

(4, 4)
Index(['name', 'age', 'city', 'score'], dtype='str')
RangeIndex(start=0, stop=4, step=1)

In [ ]:
data1 = [
    'Name':['Roshan','Vikash','Akash','Rahul'],
    'Age':[20,25,30,22],
    'Classes':[10,12,9,15],
    'Marks':[25,65,45,36]
]